image: Visual Studio 2017

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.Wire -c Release 
  - dotnet build Rebus.Wire.Tests -c Release 
